{auto_send: false, csrf_token: Ijk1MDBmOTVmMjAwZjcxMTk0MTYxYzQ4NGZiOGM2ZGZlZjA2ZjhmZDUi.Dfp9OA.nHgwy1K_1Nkksu8OICoHJ7AG85w,
  mail_host: smtp.126.com, mail_port: 25, mail_pwd: '', mail_subject: "LeoLiu_\u6D4B\
    \u8BD5\u62A5\u544A", mail_to: LeoLiu@kmhealthcloud.com, mail_user: liudinglong1989@126.com,
  report_name: test_report, submit_button: true, taffy_dir: 'D:\PycharmProjects\LeoLiu'}
